### ISSUE TITLE
Extra apostrophe in img src

### ISSUE THREAD

**Issue by viorato** [mtottrup/restaurant-pos-gas#2]
The line 206 from file script-js.html has an extra apostrophe:

It should be ` src="${item.image}"` instead of ` src="${item.image}'"`

https://github.com/mtottrup/restaurant-pos-gas/blob/5209e01fd315ef410c748f1ef44dc4d8ef5dc8ea/script-js.html#L206

**Comment by mtottrup** [comment]
Fixed thank you!

**Comment by viorato** [comment]
Your welcome! Nice code, by the way. And thanks for sharing it.
